"""Added monthly schedule events

Revision ID: 47f35386c2df
Revises: 84917b5b9a25
Create Date: 2026-06-30 15:07:08.866197

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '47f35386c2df'
down_revision = '84917b5b9a25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_schedule_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detail_id', sa.Integer(), nullable=False),
    sa.Column('meeting_type', sa.String(length=10), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('completed_on', sa.DateTime(), nullable=True),
    sa.Column('completed_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['detail_id'], ['monthly_schedule_details.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monthly_schedules', schema=None) as batch_op:
        batch_op.alter_column('generated_on',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monthly_schedules', schema=None) as batch_op:
        batch_op.alter_column('generated_on',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))

    op.drop_table('monthly_schedule_events')
    # ### end Alembic commands ###
