"""Added map color

Revision ID: 84917b5b9a25
Revises: fde1f7dea3c3
Create Date: 2026-06-30 14:45:05.162098

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '84917b5b9a25'
down_revision = 'fde1f7dea3c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedules')
    with op.batch_alter_table('areas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('map_color', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('map_order', sa.Integer(), nullable=True))
        batch_op.alter_column('area_code',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('category',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('estimated_minutes',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('display_order',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('remarks')
        batch_op.drop_column('color')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('areas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False))
        batch_op.add_column(sa.Column('remarks', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
        batch_op.alter_column('display_order',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('estimated_minutes',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30),
               nullable=False)
        batch_op.alter_column('area_code',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               existing_nullable=False)
        batch_op.drop_column('map_order')
        batch_op.drop_column('map_color')

    op.create_table('schedules',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('schedule_date', sa.DATE(), nullable=False),
    sa.Column('assignment_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('completed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('remarks', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], name=op.f('schedules_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
