"""Cascade delete monthly schedule events

Revision ID: f6108bd53280
Revises: 47f35386c2df
Create Date: 2026-06-30 15:38:55.574497

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f6108bd53280'
down_revision = '47f35386c2df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monthly_schedule_events', schema=None) as batch_op:
        batch_op.alter_column('completed',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('monthly_schedule_events_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'monthly_schedule_details', ['detail_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monthly_schedule_events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('monthly_schedule_events_ibfk_1'), 'monthly_schedule_details', ['detail_id'], ['id'])
        batch_op.alter_column('completed',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)

    # ### end Alembic commands ###
